apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubedynamicscaler-configmap-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedynamicscaler-configmap-reader-binding
subjects:
- kind: ServiceAccount
  name: kubedynamicscaler-controller-manager
  namespace: kubedynamicscaler-system
roleRef:
  kind: ClusterRole
  name: kubedynamicscaler-configmap-reader
  apiGroup: rbac.authorization.k8s.io 