# This rule is not used by the project kubedynamicscaler itself.
# It is used by users who want to grant admin permissions to other users.
#
# Grants full permissions ('*') over dynamicscaling.dynamicscaling.k8s.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubedynamicscaler
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: kubedynamicscaler-globalreplicasignore-admin-role
rules:
- apiGroups:
  - kubedynamicscaler.io
  resources:
  - globalreplicasignores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dynamicscaling.dynamicscaling.k8s.io
  resources:
  - globalreplicasignores/status
  verbs:
  - get
