---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubedynamicscaler.io
  resources:
  - globalreplicasignores
  - replicasoverrides
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubedynamicscaler.io
  resources:
  - globalreplicasignores/finalizers
  - replicasoverrides/finalizers
  verbs:
  - update
- apiGroups:
  - kubedynamicscaler.io
  resources:
  - globalreplicasignores/status
  - replicasoverrides/status
  verbs:
  - get
  - patch
  - update
