---
# Example using direct deployment reference
apiVersion: kubedynamicscaler.io/v1
kind: ReplicasOverride
metadata:
  name: nginx-test-override
spec:
  # Direct reference to a specific deployment
  deploymentRef:
    name: nginx-test
    namespace: default
  
  # Using additive mode
  overrideType: override
  
  # Add 300% more replicas
  replicasPercentage: 300